logistic_regression:
  model: LogisticRegression
  params:
    penalty: ["l2"]
    C: [0.01, 1.0, 10.0]
    solver: ["lbfgs", "liblinear"]
    max_iter: [100, 500]

random_forest:
  model: RandomForestClassifier
  params:
    n_estimators: [100, 200]
    max_depth: [10, 20]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]
    bootstrap: [True, False]

xgboost:
  model: XGBClassifier
  params:
    n_estimators: [100, 200]
    max_depth: [3, 6]
    learning_rate: [0.01, 0.1]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]
    gamma: [0, 0.1]
    reg_alpha: [0, 0.1]
    reg_lambda: [1.0, 1.5]
    tree_method: ["hist"]

svc:
  model: SVC
  params:
    C: [0.1, 1.0]
    kernel: ["linear", "rbf"]
    gamma: ["scale", "auto"]

mlp:
  model: MLPClassifier
  params:
    hidden_layer_sizes: [[50], [100, 50]]
    activation: ["tanh", "relu"]
    solver: ["adam", "sgd"]
    alpha: [0.0001, 0.001]
    learning_rate_init: [0.001, 0.01]
    max_iter: [200,200]
