DataIngestion:
  path:
    db_path: Data/data.db
    extracted_data_dir: Data/raw_data/extracted_files
    zip_path: Data/raw_data/zip_files/bank_churners.zip

  const:

DataValidation:
  path:
    schema_config_path: Config_Yaml/schema.yaml
    raw_df_path: Data/raw_data/extracted_files/bank_churners.csv

  const:

Data_Preprocessing:
  path:
    sqlite_path: "Data/data.db"             
    sqlite_table: "raw_data"                   
    processed_output_dir: "Data/processed_data" 
    tuned_output_dir: "Tuned_Model"          

  const:
    target_column: "Attrition_Flag"                    
    imputation_method: "mean"        
    categorical_imputation_method: "mode"                  
    outlier_method: "yeo"                             
    iqr_threshold: 1.5                                 
    scaler: "standard" 


DataTransformation:
  path:
    X_train_path: "Data/raw_data/preprocessed_data/X_train.csv"
    X_val_path: "Data/raw_data/preprocessed_data/X_val.csv"
    X_test_path: "Data/raw_data/preprocessed_data/X_test.csv"
    y_train_path: "Data/raw_data/preprocessed_data/y_train.csv"
    y_val_path: "Data/raw_data/preprocessed_data/y_val.csv"
    y_test_path: "Data/raw_data/preprocessed_data/y_test.csv"
    enc_scaler_path: "Tuned_Model/encoder_scaler.joblib"
    selector_path: "Tuned_Model/selector.joblib"
    extractor_path: "Tuned_Model/extractor.joblib"
    processed_data_folder: "Data/processed_data"

  const:
    sampler_method: "smote"
    selector_method: "selectkbest"
    extractor_method: "kernelpca"
    k: 20
    n_components: 15

Model_Tune_Evaluate:
  path:
    X_train_path: "Data/processed_data/X_train.csv"
    X_val_path: "Data/processed_data/X_val.csv"
    X_test_path: "Data/processed_data/X_test.csv"
    y_train_path: "Data/processed_data/y_train.csv"
    y_val_path: "Data/processed_data/y_val.csv"
    y_test_path: "Data/processed_data/y_test.csv"
    tuned_model_yaml: Config_Yaml/tuned_models.yaml
    classifiers_yaml: Config_Yaml/classifiers.yaml
    
  const:
    allowed_models: ["logistic_regression","xgboost", "random_forest", "mlp"]
    random_state: 42
    main_metric: roc_auc
    bayes_search_iter: 20

Experiment_Tracking_Prediction:
  path:
    tuned_model_yaml: Config_Yaml/tuned_models.yaml
    mlflow_details_yaml: Tuned_Model/mlflow_details.yaml
    processed_data_dir: Data/processed_data
    joblib_model_dir: Tuned_Model

  const: