DataIngestion:
  path:
    db_path: Data/data.db
    extracted_data_dir: Data/raw_data/extracted_files
    zip_path: Data/raw_data/zip_files/bank_churners.zip

  const:

DataValidation:
  path:
    schema_config_path: Config_Yaml/schema.yaml
    raw_df_path: Data/raw_data/extracted_files/bank_churners.csv

  const:

Data_Preprocessing:

  path:
    sqlite_path: "Data/data.db"             
    sqlite_table: "raw_data"                   
    processed_output_dir: "Data/processed_data"           

  const:
    target_column: "Attrition_Flag"                    
    imputation_method: "mean"        
    categorical_imputation_method: "mode"                  
    outlier_method: "yeo"                             
    iqr_threshold: 1.5                                 
    scaler: "standard" 